name: test
on: push
jobs:
  test_machine_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Telecharger code
        uses: actions/checkout@v4
      - name: Read file et afficher version docker
        run: |
          cat README.md
          docker -v
